### ISSUE TITLE
可以自动选择最高画质么？我对比了下载下来的视频和网页上的视频，看了一下，发现下载下来的画质差很多。

### ISSUE THREAD

**Issue by custs21113** [videoDown123/xiaoeknow_download#10]

**Comment by cctv180** [comment]
同问，下的是最低画质

**Comment by custs21113** [comment]
> 同问，下的是最低画质

作者不肯放出代码，不然就直接改了。
暂时先用猫抓缓存获取了，画质还行。

**Comment by cctv180** [comment]
> > 同问，下面的是最低画质
> 
> 作者不肯放代码，当然就直接改了。 暂时先用猫抓包存取了，画质还行。

没办法喽，只能等大佬更新了

**Comment by ISSIO** [comment]
> > 同问，下的是最低画质
> 
> 作者不肯放出代码，不然就直接改了。 暂时先用猫抓缓存获取了，画质还行。


不肯放出来肯定是有原因的咯

**Comment by gui8912** [comment]
放出来恐怕被别人盗用

**Comment by custs21113** [comment]
> 放出来恐怕被别人盗用

这是作者自己写的
![image](https://github.com/videoDown123/xiaoeknow_download/assets/38849744/ab69015c-1313-43f2-a969-2b5ae53c99c3)
代码没贴出来，谁知道他怎么实现的，更遑论优化他的代码。
都几个月前的issue了，我的建议是别挖坟了，并且我也给出了另外一种实现需求的方式。
使用猫抓插件通过缓存获取视频文件，画质可以到达高清。
